#!/bin/sh

i3-save-tree --workspace 1 > ~/.config/i3/workspace_1.json
sed -i 's|^\(\s*\)// "|\1"|g; /^\s*\/\//d' ~/.config/i3/workspace_1.json
i3-save-tree --workspace 2 > ~/.config/i3/workspace_2.json
sed -i 's|^\(\s*\)// "|\1"|g; /^\s*\/\//d' ~/.config/i3/workspace_2.json
i3-save-tree --workspace 3 > ~/.config/i3/workspace_3.json
sed -i 's|^\(\s*\)// "|\1"|g; /^\s*\/\//d' ~/.config/i3/workspace_3.json

